config/routes.rb
SampleApplication::Application.routes.draw do

  get "chats/index"
  get "chats/send_data"

  get "networks/index"
  get "networks/edit"

  get "emails/remind"
  get "emails/correspond"

  get "friendships/initiate"
  get "friendships/accept"
  get "friendships/decline"
  get "friendships/cancel"
  get "friendships/delete"

  get "faqs/index"
  get "faqs/edit"

  resources :emails do
    member do
      get "correspond" #enable using rout helper 'correspond_email_path' 
    end
  end

  resources :faqs
  resources :specs

  resources :users do
    member do
      get :friends
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :profiles
  resources :friendships
  resources :networks
  resources :chats
  resources :preferences
  resources :posts

  match "/signup", :to=> "users#new"
  match "/signin", :to => "sessions#new"
  match "/signout", :to => "sessions#destroy"
  match "/home", :to=>"pages#home"
  match "/help", :to =>"pages#help"
  match "/contact", :to =>"pages#contact"
  match "/about", :to =>"pages#about"
  match "/request", :to =>"friendships#create"
  match "/emails/remind", :to =>"emails#remind"
  match "/emails/correspond", :to => "emails#correspond"
  match "/friendships/initiate", :to => "friendships#initiate"
  match "/friendships/accept", :to => "friendships#accept"
  match "/friendships/delete", :to => "friendships#delete"
  match "/chats/send_data", :to => "chats#send_data"
  match "/preferences/edit", :to => "preferences#edit"
  match "/preferences/show", :to => "preferences#show"

  root :to => "pages#home"

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :posts, :dependent => :destroy
  has_many :microposts, :dependent => :destroy

  has_many :comments

  has_one :spec, :dependent => :destroy

  has_one :faq, :dependent => :destroy

  has_one :network, :dependent => :destroy

  has_one :preference, :dependent => :destroy

  has_many :friendships, :dependent => :destroy

  has_many :friends,
           :through => :friendships,
           :conditions => "status = 'accepted'",
           :order => :name
  has_many :requested_friends,
           :through => :friendships,
           :source => :friend,
           :conditions => "status = 'requested'",
           :order => :initiated_at
  has_many :pending_friends,
           :through => :friendships,
           :source => :friend,
           :conditions => "status = 'pending'",
           :order => :initiated_at
  
  email_regex = /\A[\w+\-.]+@[a-z\-.\d]+\.[a-z]+\z/i
  
  validates :name, :presence=> true,
                   :length=>{:maximum=>30}
  
  validates :email, :presence=> true,
                    :format => {:with=> email_regex},
                    :uniqueness => {:case_sensitive => false}
  validates :password, :presence=>true,
                       :length=>{:within => 6..40},
                       :confirmation =>true

  before_save :encrypt_password  #callback function to save the encrypted password  
  
  #def protect_against_forgery?
    #false
  #end

  def self.authenticate(email, submitted_password) #fetches user with the email given and compares emails corresponding encrypted_password with encrypted version of submitted password 
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  #verifies user with id param has same salt as salt in the cookie
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def has_password? (submitted_password) #compares an encrypted version of submitted password with encrypted_password in database. 
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.is_same?(user, friend)
    user == friend
  end


  private

  def encrypt_password #encrypt the virtual attribute password and assign to encrypted_password 
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string) #encrypt the password parameter given using the user's salt 
    secure_hash("#{salt}--#{string}")
  end

  def make_salt #create a salt attribute for user identification using current time and virtual password attribute 
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string) #function to perform the encryption process. 
    Digest::SHA2.hexdigest(string)
  end
end


# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index,:show, :edit, :update] #non members can only sign up to platform 
  before_filter :correct_user, :only => [:edit, :update] #member actions require current_user 
  before_filter :admin_user, :only=> :destroy

  #displays a view of all users of the platform
  def index
    @title = "All users"
    #@users = User.all
    @users = User.all.paginate :page => params[:page], :per_page => 10 #implements pagination with will_paginate gem 
    respond_to do |format|
      format.html {render :index}
      format.js
    end
  end

  #renders a new view to sign up new users
  def new
    @title="Sign Up"
   @user = User.new
  end

  def show
    @user = User.find(params[:id])
    #edit links will show if user is viewing his own profile
    @hide_edit_links = true unless current_user?(@user)
    @friends = @user.friends
    @requested_friends = @user.requested_friends
    @pending_friends = @user.pending_friends
    @title = @user.name
    @spec = @user.spec ||= Spec.new
    @faq = @user.faq ||= Faq.new
    @network = @user.network ||= Network.new
    @preference = @user.preference ||= Preference.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      sign_in @user #assigns @user tp current_user 
      flash[:success] = "Welcome to the network, #{@user.name}"
      redirect_to @user
    else
      flash[:error] = "Signup not successful"
      @title = "Sign up"
      render 'new'
    end

  end

  def edit
    #@user = User.find(params[:id]) #already defined in correct_user filter 
    @title = "Edit user"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted successfully."
    redirect_to users_path
  end

  def friends

    @user = User.find(params[:id])
    @friends = @user.friends.paginate :page => params[:page]

    if @friends.empty?
      flash[:notice] = "There are no friends to display"
      respond_to do |format|
        format.html {redirect_to profile_path(@user)}
        format.js
      end
      #redirect_to profile_path(@user)
    end

    #respond_to do |format|
      #format.html
      #format.js
    #end
    #redirect_to profile_path(@user)
  end



  #private

    def authenticate
      deny_access unless signed_in?
    end

  #redirects signed in users who attempt unauthorized access.
  def correct_user
    @user = User.find(params[:id])
    #redirect_to (root_path) unless current_user?(@user)
    unless current_user?(@user)
      flash[:error] = "The requested page is unauthorized"
      redirect_to(user_path(current_user))
      #redirect_to root_path
    end
  end
    #redirects signed in users who attempt unauthorized access.
    #def correct_user
      #@user = User.find(params[:id])
      #redirect_to (root_path) unless current_user?(@user)
      #unless current_user?(@user)
        #flash[:error] = "The requested page is unauthorized"
        #redirect_to(user_path(current_user))
        #redirect_to root_path
      #end
    #end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {:size=> 50}) 
    gravatar_image_tag(user.email.downcase, :alt =>user.name,
                                            :class => 'gravatar',
                                            :gravatar=>options)
  end

  #def submit_text 
    #@user.new_record? "Sign up" : "Edit"
  #end

  def submit_text
    unless @user.new_record?
      "Edit"
    else
      "Sign up"
    end

  end
end

app/views/users/_friend.haml
%tr
  %td
    = gravatar_for friend, :side => 30
    = link_to friend.name, profile_path(friend)
  %td
    = unless hide_edit_links?
      = link_to "Delete", {:controller => "friendship",
            :action => "delete", :id => friend.id},
            :confirm => "Delete friendship with #{friend.name}?"

app/views/users/_user.haml
%tr

  %td
    = link_to (gravatar_for user, :size => 80), profile_path(user)
    -#%br/
  %td
    = link_to user.name, profile_path(user)

  %td
    = friendship_action(current_user, user)

  %td
    - if current_user.admin?
      = link_to "delete", user, :method => :delete,
      :confirm => "Are you sure?", :title => "Delete #{user.name}"

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? -%>
    <%= link_to "delete", user, :method => :delete,
      :confirm => "Are you sure?", :title => "Delete #{user.name}"%>
  <% end -%>
</li>

app/views/users/_usser.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? -%>
    <%= link_to "delete", user, :method => :delete,
      :confirm => "Are you sure?", :title => "Delete #{user.name}"%>
  <% end -%>
</li>

app/views/users/eddit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render "new_or_edit_form", :f => f %>
<% end -%>

<div>
  <%= gravatar_for @user %>
  <a href = "http://gravatar.com/emails">change</a>
</div>

app/views/users/edit.haml
%fieldset.push-9
  %legend Edit user
  = form_for(@user) do |f|
    =render "new_or_edit_form", :f => f

  %div
    = gravatar_for @user
    %a{:href => "http://gravatar.com/emails", :target=>"_blank"}
      change

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render "new_or_edit_form", :f => f %>
<% end -%>

<div>
  <%= gravatar_for @user %>
  <a href = "http://gravatar.com/emails">change</a>
</div>

app/views/users/friends.js.erb
<%#$("middle_side").update("<%=escape_javascript(render('users/friends'))")%>
$("middle_side").update("Whats up?")

app/views/users/index.haml
.pagination.push-6.span-12
  = will_paginate
  %fieldset
    %legend
      Members
    %table.box
      = render @users #rails automatically iterates via @users and renders _user.html.erb partial 

  = will_paginate

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate  %>

<ul class = "users">

  <%= render @users %> <%#rails automatically iterates via @users and renders _user.html.erb partial%> 
</ul>


<%= will_paginate  %>

app/views/users/inndex.html.erb
<h1>All users</h1>

<%= will_paginate  %>

<ul class = "users">

  <%= render @users %> <%#rails automatically iterates via @users and renders _user.html.erb partial%> 
</ul>


<%= will_paginate  %>

app/views/users/new.haml
%fieldset.push-9
  %legend
    Sign up

  = form_for(@user) do |f|
    = render "new_or_edit_form", :f => f #passing the form as a local variable accessible in the partial

app/views/users/show.haml
#left_side.span-5.prepend-top.border
  #gravatar.box
    = gravatar_for (@user, :size=>150)
    - unless hide_edit_links?
      %a{:href => "http://gravatar.com/emails", :target=>"_blank"}
        change
    -#%br/
  %p.push-1
    = @spec.full_name
    %br/
    %strong
      =@spec.occupation
      %hr/
  = link_to "#{@user.name}\'s info", user_path(@user)
  %br/
  -#= friendship_status(current_user, @user) if !User.is_same?(@user, current_user)
  = friendship_status(current_user, @user) unless current_user?(@user)
  %br/
  = link_to "send user a mail", :controller =>"emails",
            :action =>"correspond", :id =>@user unless current_user?(@user)
  %br/

  - unless Friendship.exists?(current_user, @user) or current_user?(@user)
    = link_to "Add #{@user.name} as friend",{:controller =>"friendships", :action =>"initiate",
                   :id => @user.id}, :confirm => "Add #{@user.name} as friend?"
  %hr/
  #bio
    %h2
      My Bio
    = sanitize @faq.bio
    -#%hr/
    - unless hide_edit_links?
      %span.edit_link
        = link_to "(edit)", edit_faq_path(@user)


  -#mutual friends are displayed only when in profile view mode 
  - if hide_edit_links? and !current_user?(@user)
    = render 'friendships/mutual_friends' 
  %hr/

  = render 'friendships/friends' 

#middle_side.span-14.prepend-top.append-bottom.border
  %fieldset
    %legend
      Basic User Info
    %table
      %tr
        %td.label
          Screen Name:
        %td
          = @user.name
      %tr
        %td.label
          Email:
        %td
          = @user.email
      - if current_user?(@user)
        %tr
          %td.label
            Password:
          %td
            ******
    - unless hide_edit_links?
      %span.edit_link
        = link_to "edit", edit_user_path(@user)

  %fieldset
    %legend
      Networks
    %table
      %tr
        %td
          Facebook:
        %td
          = @network.facebook
      %tr
        %td
          Twitter:
        %td
          = @network.twitter
      %tr
        %td
          LinkedIn:
        %td
          = @network.linkedin
      %tr
        %td
          Youtube:
        %td
          = @network.youtube

    - unless hide_edit_links?
      %span.edit_link
        = link_to "edit", edit_network_path(@user)

  %fieldset
    %legend
      User Spec
    %table
      -#= render 'specs/field_row', :collection => Spec::ALL_FIELDS
      - Spec::ALL_FIELDS.each do |field|
        = render 'specs/field_row', :field_row => field
    - unless hide_edit_links?
      %br/
      %span.edit_link
        = link_to "edit", edit_spec_path(@user)
  - Faq::FAVOURITES.each do |favourite|
    = render 'faqs/sidebar_box', :sidebar_box => favourite
    %hr/

  - unless hide_edit_links? #preference are not to be shown in settings mode 
    %fieldset
      %legend
        Preferences
      %table
        %tr
          %td
            Show Profile to:

          %td
            = @preference.profile_view

      %span.edit_link
        = link_to "edit", edit_preference_path(@user)

#right_side.span-4.prepend-top.last.append-bottom
  %hr/
  Notifications and ads will be here
  mobile monday this friday
  saturday mesters follow the link
  = link_to "Saturday MESTers", "www.google.com"
  %hr/

app/views/users/sshow.html.erb
<div id= "left_side">
  <h1>
    <div id= "gravatar">
      <%= gravatar_for (@user) %>
      <br />
      <%= @user.name %>
    </div>
  </h1>
</div>

<div id="middle_side">
  main content goes here!!
</div>

<div id="right_side">
  notifications and ads here!!
</div>